### PR TITLE
feat: adds types to Nuxt config

### LINKED ISSUE #1347: Add type support to nuxt.config.ts
`nuxt.config.ts` can be typed.

```ts
import { Configuration } from '@nuxt/types'

const config: Configuration = {
  // ...
}

export default config
```

### PR DESCRIPTION
**Pull request by moltar**
Closes #1347 

But could not test properly due to #1350

### CODE REVIEW

**Comment by moltar** [comment]
Not sure what to do about:

```
/code/nuxt.config.ts

  111:12  error    Method 'extend' has a complexity of 7  complexity
```

The complexity is necessary, because `config.resolve` and `config.resolve.alias` and `config.module` and `config.plugins` can all be `undefined`.

If we don't check for that with `if`, then TypeScript complains about it.

The only solution I can think of is `eslint-ignore`. But I try to avoid that whenever possible.

Any other ideas about fixing the complexity?

**Comment by moltar** [comment]
Also, ` template/package-lock.json` diff seems extremely large.

Any ideas?

Could be due to `save-exact=true` in my `~/.npmrc`.

**Comment by moltar** [comment]
Not sure what to do, but even just doing `npm i` on a fresh checkout rewrites the `package-lock.json` file immensely.

And cannot use `npm ci`, because:

```
❯ npm ci
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "{{ name }}": name can only contain URL-friendly characters

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/~/.npm/_logs/2019-10-07T18_41_20_432Z-debug.log
```

Let me know how you add deps to the template itself and I'll try to reproduce using your steps.

I have also tried installing without `.npmrc`.

And, just in case:

```
❯ npm -v

6.11.3
```

**Comment by moltar** [comment]
Basically, try the following in a new dir:

```
git clone git@github.com:wemake-services/wemake-vue-template.git
cd wemake-vue-template/template
npm i
git diff --stat package-lock.json
```

I get:

```
❯ git diff --stat package-lock.json
 template/package-lock.json | 26643 ++++++++++++++---------------------------------------------------------------------------------------
 1 file changed, 3593 insertions(+), 23050 deletions(-)
```

Could it be that the lock file is obsolete?

**Comment by sobolevn** [comment]
I use this technique: 
1. When I work inside the `template/` dir I change `{{ name }}` to `name` inside `package.json`
2. Then it is possible to use `npm` freely
3. In the end, change `name` back to `{{ name }}`

I guess, that this should live in `CONTRIBUTING.md`, so future contributors will know this trick.

**Comment by moltar** [comment]
Ok, but need to remember that `package-lock` file also includes the name of the package. So that might be why it is completely overwriting it, as it sees a package name change.

**Comment by moltar** [comment]
Ok, editing names by hand worked!

**Comment by sobolevn** [comment]
Thanks!

**Pull request merged**
